
[build]
  command = "npm run build"
  publish = "dist"

# Handles routing for single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure proper MIME types for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
